version: '3'
services:
  web:
    build: .

  cypress:
    build:
      context: .
      dockerfile: cypress/Dockerfile
    depends_on:
    - web
    volumes:
    - .:/app
    environment:
      - CYPRESS_baseUrl=http://web
  